# Site settings
title: "BuzzMeow"
email: "your-email@example.com"
description: "BuzzMeow — Trending blogs, stories, and insights powered by Reddit and beyond."
url: "https://buzzmeow.com"   # your custom domain
baseurl: ""                   # leave empty for root domain

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Author info
author:
  name: "BuzzMeow Team"
  avatar: "/assets/images/avatar.png" # optional (remove if no image yet)
  bio: "We curate top stories from Reddit & across the web."
  location: "Worldwide"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/meet-furia"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/your-handle"

# Layout defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

# Minimal Mistakes theme settings
minimal_mistakes_skin: "default"   # skins: air, aqua, contrast, dark, dirt, neon, sunrise, etc.
search: true
